title: Lessons in Pygame
description: Introductory lesson to Pygame
theme: just-the-docs

url: https://joshuacussen.github.io/pygame

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
